// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXJlRB_x0_ya70glnX4rbpkgQQv4T0u_U',
    appId: '1:447609286723:web:ac1597500f9363f132a4f6',
    messagingSenderId: '447609286723',
    projectId: 'food-delivery-bf0bb',
    authDomain: 'food-delivery-bf0bb.firebaseapp.com',
    storageBucket: 'food-delivery-bf0bb.appspot.com',
    measurementId: 'G-6BFTRH5KNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArG8N0AIDeulsRd_NObxBv9u8-KesWXSk',
    appId: '1:447609286723:android:0da3548a26c58e0632a4f6',
    messagingSenderId: '447609286723',
    projectId: 'food-delivery-bf0bb',
    storageBucket: 'food-delivery-bf0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0oSCQ4tOzYCgpldtfbQef4TV1SfjeQrs',
    appId: '1:447609286723:ios:461781395b6ae17932a4f6',
    messagingSenderId: '447609286723',
    projectId: 'food-delivery-bf0bb',
    storageBucket: 'food-delivery-bf0bb.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0oSCQ4tOzYCgpldtfbQef4TV1SfjeQrs',
    appId: '1:447609286723:ios:461781395b6ae17932a4f6',
    messagingSenderId: '447609286723',
    projectId: 'food-delivery-bf0bb',
    storageBucket: 'food-delivery-bf0bb.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXJlRB_x0_ya70glnX4rbpkgQQv4T0u_U',
    appId: '1:447609286723:web:905cf6325d2a142e32a4f6',
    messagingSenderId: '447609286723',
    projectId: 'food-delivery-bf0bb',
    authDomain: 'food-delivery-bf0bb.firebaseapp.com',
    storageBucket: 'food-delivery-bf0bb.appspot.com',
    measurementId: 'G-MHKC46HNND',
  );
}
